### ISSUE TITLE
Testsuite crashes when TestNG cannot resolve dependencies

### ISSUE THREAD

**Issue by tomg246** [telekom/testerra#177]
**Description**

When dependencies are wrong or (see example below) a certain mix of groupDependencies and inheritance is used, the whole suite crashes instead of only skipping the affected tests.
Bug was found with XETA 9.7 (TestNG 3.12.).
Most likely it is TestNG issue and Testerra can do nothing about it.

**Example**
We use collectMethods to collect data and a bunch of tests to assert different aspects of this data. 
We also use inheritance for different shops and languages, so in some subclasses the collectMethod is overridden, in some some tests are overridden. This has to be done via groupDependency, as normal dependsOnMethods doesn't work with inheritance.

The following setting runs ok when the suite.xml is executed via intelliJ but crashed the run at night:

```java
public abstract class AbstractClass(){
  @Test(groups = "myGroup")
  abstract void collect();

  @Test(dependsOnGroups = "myGroup")
  public void test1() {
       //do something
  }
}

public class SubClass extends AbstractClass{
  @Test(groups = "myGroup")
  public void collect(){
    //some implementation
  }

  @Test(dependsOnGroups = "myGroup")
  public void test2() {
       //do something
  }
}
```

When executing a suite which contains the class Subclass, the suite crashes, complaining that test1 depends on a group that doesn't exist.
When all methods have ignoreMissingDependencies = true, the setup works.

**Expected Behaviour**
Best case: tests are skipped instead, suite conitnues
Alternative: Exectution in intelliJ and on TAP behave alike.

**Stacktrace**
```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project regressiontest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
org.testng.TestNGException: 
  
DependencyMap::Method "AbstractOvTrackingTest.test_ov_categories_home()[pri:0, instance:eu.tsystems.mms.project.tests.tracking.datalayer.tests.ov.ProjectOvTrackingTest@592a1882]" depends on nonexistent group "collectCategories"
    at org.testng.DependencyMap.getMethodsThatBelongTo(DependencyMap.java:43)
    at org.testng.TestRunner.createDynamicGraph(TestRunner.java:1075)
    at org.testng.TestRunner.privateRun(TestRunner.java:747)
    at org.testng.TestRunner.run(TestRunner.java:634)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
    at org.testng.SuiteRunner.run(SuiteRunner.java:334)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
    at org.testng.TestNG.runSuites(TestNG.java:1161)
    at org.testng.TestNG.run(TestNG.java:1129)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
    at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by mreiche** [comment]
NOTE: Please do not provide links to internal resources.

**Comment by gogro** [comment]
this is not Testerra-related.
