### ISSUE TITLE
Report generation fails, if path to local maven repository contains spaces

### ISSUE THREAD

**Issue by arbu** [telekom/testerra#33]
**Describe the bug**
We recently switched from the report module to report-ng. Since then no report is generated when running inside a Jenkins-Pipeline which contains spaces in its name. This seems to be caused by an improperly escaped path to the report-ng jar file.

**To Reproduce**
1. Clone the testerra-skeleton repo
2. Create a directory with a space in it, e.g. `C:\Local Maven Repo`
3. Run maven inside the skeleton project with this directory as local repo: `mvn  -Dmaven.repo.local="C:\Local Maven Repo" test -PmySuite`

**Expected behavior**
A report to be present in the target directory.

**Actual behavior**
No report is present and the following stacktrace is logged:
```
2021-04-27 21:06:18,328 [main] ERROR eu.tsystems.mms.tic.testframework.listeners.CopyReportAppListener - Unable to copy app resource
java.lang.IllegalArgumentException: Illegal character in opaque part at index 49: jar:file:/var/lib/jenkins/workspace/Test-Pipeline Abnahme/.repository/eu/tsystems/mms/tic/testerra/report-ng/1-SNAPSHOT/report-ng-1-SNAPSHOT.jar
	at java.net.URI.create(URI.java:852)
	at eu.tsystems.mms.tic.testframework.listeners.CopyReportAppListener.getPathsFromResourceJAR(CopyReportAppListener.java:83)
	at eu.tsystems.mms.tic.testframework.listeners.CopyReportAppListener.onFinalizeExecution(CopyReportAppListener.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at eu.tsystems.mms.tic.testframework.report.TesterraListener.generateReport(TesterraListener.java:418)
	at org.testng.TestNG.generateReports(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1042)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 49: jar:file:/var/lib/jenkins/workspace/Test-Pipeline Abnahme/.repository/eu/tsystems/mms/tic/testerra/report-ng/1-SNAPSHOT/report-ng-1-SNAPSHOT.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 22 common frames omitted
```

**Environment(please complete the following information):**
 - OS: CentOS 7
 - Version 1-SNAPSHOT

**Additional Information:**
From my research this could probably be fixed by changing the line https://github.com/telekom/testerra/blob/4db3879d0e0c41d7a11d091811a97e78de999e56/report-ng/src/main/java/eu/tsystems/mms/tic/testframework/listeners/CopyReportAppListener.java#L78 from `getPath()` to `getRawPath()`, i.e. using the already escaped path component of the URI. But I was not yet able to confirm this myself, as I had some issues building the module.

**Comment by mreiche** [comment]
Nice, can you provide a PR for that?

**Comment by arbu** [comment]
When I build the master branch locally with `gradle -Dmaven.repo.local="C:/Local Maven Repo" publishToMavenLocal` it results in the file `report-ng-1-SNAPSHOT.jar` not containing the folder report-ng. This causes the generation of the report to fail a few lines later in CopyReportAppListener.java with `java.nio.file.NoSuchFileException: report-ng`. From that I assume, that at least the escaped path of the jar works. I can create a PR for this if wanted, but I cannot assure this is working properly.
Btw, I am running Gradle 6.6 with AZUL JDK 11 from Git Bash, if that helps.

**Comment by mreiche** [comment]
Did you run `gradle buildReport` before `gradle build` as described in `README.md`?

**Comment by arbu** [comment]
That did the trick. It wasn't quite obvious from the readme, that this step is required for every kind of building. I will create a PR then.
