### ISSUE TITLE
Problem with concurrent acces on GuiElementData.WEBELEMENT_MAP and generall blocking problem with Times.executeSequence

### ISSUE THREAD

**Issue by radzimir** [telekom/testerra#51]
Two threads ar hanging while concurently acessing GuiElementData.WEBELEMENT_MAP.

  
```
 java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.WeakHashMap.expungeStaleEntries(WeakHashMap.java:319)
	- waiting to lock <0x0000000081efa530> (a java.lang.ref.ReferenceQueue)
	at java.util.WeakHashMap.getTable(WeakHashMap.java:350)
	at java.util.WeakHashMap.put(WeakHashMap.java:450)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.setWebElement(DesktopGuiElementCore.java:168)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.find(DesktopGuiElementCore.java:122)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.getWebElement(DesktopGuiElementCore.java:211)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.find(DesktopGuiElementCore.java:107)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.isPresent(DesktopGuiElementCore.java:546)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.pIsDisplayed(DesktopGuiElementCore.java:447)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.core.DesktopGuiElementCore.isDisplayed(DesktopGuiElementCore.java:443)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.waiters.StandardGuiElementWait$4.run(StandardGuiElementWait.java:132)
	at eu.tsystems.mms.tic.testframework.utils.Timer.executeSequence(Timer.java:161)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.TimerWrapper.executeSequence(TimerWrapper.java:95)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.waiters.StandardGuiElementWait.pWaitForDisplayedStatus(StandardGuiElementWait.java:139)
	at eu.tsystems.mms.tic.testframework.pageobjects.internal.waiters.StandardGuiElementWait.waitForIsDisplayed(StandardGuiElementWait.java:117)

```

I can be caused by some bug in JVM, but It's of course hard to analyse. 

I have two suggestions:

1. Pls. change GuiElementData.WEBELEMENT_MAP from static to thread local as workaround to minimize risk. 

2. In Times.executeSequence line 161 the task is executed directly in the same thread, so it blocks if task does'n return violating "time over" expectation. This could be rafactored to make a use of parallel thread. If needed, I could provide an implemmentatnion for that, pls. simply contact me.

**Comment by mreiche** [comment]
0. What kind of JVM bug is that? Is it filed somewhere?

1. The GuiElementMap cannot be thread local for reasons, but you could try to make it a `ConcurrentHashMap`.

2. We dont want to have threads in these sequences.
